import type { Locale } from '../../../shared/i18n';

const english = {
  steps: ['Choose a starting point', 'Configure Agent', 'Configure environment', 'First API call'],
  title: 'Start with your first Agent',
  subtitle: 'Choose a starting point, configure its environment, then connect it to your application.',
  recommended: 'Recommended',
  firstStart: 'Start here for your first call',
  scenarios: 'More scenarios',
  ready: 'Preconfigured, ready to customize',
  start: 'Start configuring',
  back: 'Back',
  next: 'Create and continue',
  reuse: 'Use existing and continue',
  name: 'Name',
  description: 'Description (optional)',
  model: 'Model',
  system: 'System prompt',
  agentTitle: 'Configure Agent',
  agentSubtitle: 'Choose a model and tell your Agent how to help.',
  environmentTitle: 'Configure the runtime environment',
  environmentSubtitle: 'Choose an existing environment or create one for this Agent.',
  newEnvironment: 'Create a new environment',
  environmentName: 'Environment name',
  existing: 'Existing environment',
  existingAgent:
    'Agents with this name already exist. Select one to use its saved configuration, or create a new Agent.',
  newAgent: 'Create a new Agent',
  usingAgent: 'Using the saved configuration. To customize it, choose Create a new Agent.',
  required: 'Fill in the name, model and system prompt to continue.',
  modelUnavailable:
    'This model is no longer available. Choose an available model for a new Agent, or update the existing Agent.',
  environmentRequired: 'Choose an environment or enter a name to create one.',
  archivedName:
    'An archived environment already uses this name. Choose another name or manage the existing environment.',
  saved: 'Configuration saved',
  api: 'Corresponding API request',
  apiHint: 'Application example: replace YOUR_API_KEY. This page uses your signed-in account.',
  integrationTitle: 'Run your first conversation',
  integrationSubtitle: 'Test here with your signed-in account, or use these requests in your application.',
  apiCalls: 'Application API calls',
  key: 'Prepare an API key',
  keyHint:
    'Open API keys for the current workspace to create a key, or use an existing one. Replace YOUR_API_KEY in the examples.',
  keyLink: 'Go to API keys',
  createSession: 'Create a session',
  createSessionHint:
    'Run this request first to create a conversation with this Agent and environment. The response id is the Session ID used in requests 2 and 3; no Session ID is needed here.',
  listen: 'Receive replies',
  listenHint: 'Open this stream in terminal A before sending. It remains open for live events.',
  sendMessage: 'Send a message',
  sendHint: 'Once terminal A shows connected, send this request in terminal B.',
  sessionID: 'Session ID',
  sessionIDPlaceholder: 'Paste id from the create response',
  sessionIDHint:
    'Run request 1, then paste the response id. Receiving and sending use the same ID to address this conversation. The online test creates its own session automatically.',
  test: 'Online test',
  testHint: 'Uses your signed-in account. No API key needed.',
  firstMessage: 'Send your first message',
  suggested: 'Hello! What can you help me with?',
  message: 'Test message',
  send: 'Send',
  stop: 'Stop',
  newSession: 'Start a new test conversation',
  viewSession: 'View session',
  viewAgent: 'View Agent',
  sending: 'Preparing and sending…',
  running: 'Agent is working…',
  complete: 'First conversation completed',
  stopped: 'Test stopped',
  retry: 'Retry',
  unknown:
    'The request result is not confirmed. Check for its saved result before continuing; it will not be submitted again automatically.',
  recover: 'Check saved result',
  notFound: 'No confirmed result was found yet. Retry checking, or inspect your resources before starting again.',
  duplicate: 'More than one saved result was found. Choose the intended resource in the console.',
  storage: 'This browser cannot save progress. Keep this page open until requests finish.',
  restore: 'Checking saved resources…',
  restoreFailed: 'A saved resource is no longer available. Select an available resource to continue.',
  copy: 'Copy request',
  copied: 'Copied',
  copyFailed: 'Select the code to copy it manually.',
  limited: 'Limited network access',
  unrestricted: 'Unrestricted network access',
  cloud: 'Cloud sandbox',
  selfHosted: 'Self-hosted sandbox',
  selfHostedHint: 'Requires an available self-hosted execution service.',
  newEnvironmentHint: 'Uses the standard cloud environment with limited network access.',
  emptyEnvironments: 'No active environments. Create one to continue.',
  reused: 'Use existing',
  received: 'Message accepted; waiting for the Agent',
  unknownMessage: 'Sending was not confirmed. Refresh the conversation before explicitly sending again.',
  connectionTimeout: 'The conversation did not connect in time. Retry when the event stream is available.',
  refresh: 'Refresh conversation',
  reviewed: 'I reviewed the conversation; enable sending',
  failedTurn: 'The Agent stopped with an error. Review the conversation before retrying.',
};

const chinese: typeof english = {
  steps: ['选择起始点', '配置 Agent', '配置环境', '第一个 API 调用'],
  title: '从第一个 Agent 开始',
  subtitle: '选一个起点，配置运行环境，再把 Agent 接入你的应用。',
  recommended: '推荐',
  firstStart: '第一次使用，从这里开始',
  scenarios: '更多应用场景',
  ready: '已预填配置，可按需修改',
  start: '开始配置',
  back: '返回',
  next: '创建并继续',
  reuse: '使用已有，下一步',
  name: '名称',
  description: '描述（可选）',
  model: '模型',
  system: '系统提示词',
  agentTitle: '配置 Agent',
  agentSubtitle: '选择模型，告诉 Agent 如何完成任务。',
  environmentTitle: '配置运行环境',
  environmentSubtitle: '选择已有环境，或为这个 Agent 新建环境。',
  newEnvironment: '新建环境',
  environmentName: '环境名称',
  existing: '已有环境',
  existingAgent: '已找到同名 Agent。可以选择复用已有配置，也可以新建一个 Agent。',
  newAgent: '新建一个 Agent',
  usingAgent: '正在使用已有配置。如需调整，请选择新建一个 Agent。',
  required: '请填写名称、模型和系统提示词后继续。',
  modelUnavailable: '此模型已不可用。请为新 Agent 选择可用模型，或先更新已有 Agent。',
  environmentRequired: '请选择环境，或填写新环境名称。',
  archivedName: '归档环境已占用此名称。请修改名称，或管理已有环境。',
  saved: '配置已保存',
  api: '对应 API 调用',
  apiHint: '应用接入示例：需替换 YOUR_API_KEY。页面内操作使用当前登录账号。',
  integrationTitle: '运行你的第一次对话',
  integrationSubtitle: '使用当前登录账号在线测试，或将这些请求接入你的应用。',
  apiCalls: '应用 API 调用',
  key: '准备 API 密钥',
  keyHint: '前往当前工作区的「API 密钥」页面创建密钥，也可以使用已有密钥。将示例中的 YOUR_API_KEY 替换为你的密钥。',
  keyLink: '前往 API 密钥页面',
  createSession: '创建会话',
  createSessionHint:
    '先执行此请求，为当前 Agent 和环境创建一次对话。响应中的 id 就是第 2、3 个请求需要的 Session ID；这一步不需要填写 Session ID。',
  listen: '获取回复',
  listenHint: '先在终端 A 打开事件流，再发送消息。此连接会持续接收实时事件。',
  sendMessage: '发送消息',
  sendHint: '终端 A 显示 connected 后，在终端 B 发送此请求。',
  sessionID: 'Session ID（会话标识）',
  sessionIDPlaceholder: '粘贴创建会话响应中的 id',
  sessionIDHint:
    '先执行第 1 个请求，再粘贴响应中的 id。获取回复和发送消息共用这个 ID，以指定同一次对话。在线测试会自动创建自己的会话，无需填写。',
  test: '在线测试',
  testHint: '使用当前登录账号测试，无需填写 API 密钥。',
  firstMessage: '发送第一条消息',
  suggested: '你好，告诉我你能做什么。',
  message: '测试消息',
  send: '发送',
  stop: '停止',
  newSession: '开始新的测试对话',
  viewSession: '查看会话',
  viewAgent: '查看 Agent',
  sending: '正在准备并发送…',
  running: 'Agent 正在执行…',
  complete: '第一次对话已完成',
  stopped: '测试已停止',
  retry: '重试',
  unknown: '请求结果尚未确认。请先检查已保存结果；系统不会自动重复提交。',
  recover: '检查已保存结果',
  notFound: '暂未找到已确认的结果。请再次检查，或先在控制台核对资源。',
  duplicate: '发现多个保存结果，请在控制台选择正确资源。',
  storage: '此浏览器无法保存进度。请保持页面打开，直到请求完成。',
  restore: '正在检查已保存的资源…',
  restoreFailed: '已保存的资源不再可用，请重新选择可用资源。',
  copy: '复制请求',
  copied: '已复制',
  copyFailed: '请选中代码手动复制。',
  limited: '受限网络访问',
  unrestricted: '不受限网络访问',
  cloud: '云端沙箱',
  selfHosted: '自托管沙箱',
  selfHostedHint: '需要可用的自托管执行服务。',
  newEnvironmentHint: '使用标准云端环境与受限网络访问。',
  emptyEnvironments: '暂无可用环境，请新建环境后继续。',
  reused: '复用已有',
  received: '消息已接受，正在等待 Agent',
  unknownMessage: '尚未确认发送结果。请先刷新对话，再明确决定是否重新发送。',
  connectionTimeout: '对话未能及时连接，请在事件流可用后重试。',
  refresh: '刷新对话',
  reviewed: '我已核对对话，允许再次发送',
  failedTurn: 'Agent 执行失败，请查看对话后再决定是否重试。',
};

export function quickstartCopy(locale: Locale) {
  return locale === 'zh-CN' ? chinese : english;
}
