#!/usr/bin/env bash

set -euo pipefail

source_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
temp_root="$(mktemp -d)"
trap 'rm -rf "$temp_root"' EXIT

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

new_repo() {
  local name="$1"
  local repo="$temp_root/$name"

  mkdir -p "$repo/scripts"
  git -C "$repo" init -q
  cp "$source_root/scripts/check-go-file-lines.sh" "$repo/scripts/check-go-file-lines.sh"
  chmod +x "$repo/scripts/check-go-file-lines.sh"
  printf '# Exact legacy ratchets: <lines> <tracked Go path>\n' > "$repo/scripts/go-file-line-budgets.txt"
  printf '%s\n' "$repo"
}

make_lines() {
  local path="$1"
  local lines="$2"
  awk -v lines="$lines" 'BEGIN { for (i = 1; i <= lines; i++) print "// line " i }' > "$path"
}

assert_rejected() {
  local repo="$1"
  local expected="$2"
  local output

  if output="$(cd "$repo" && ./scripts/check-go-file-lines.sh 2>&1)"; then
    fail "expected $expected to be rejected"
  fi
  [[ "$output" == *"$expected"* ]] || fail "failure output did not name $expected"
}

# Failure scenarios precede success scenarios.
repo="$(new_repo oversized-production)"
make_lines "$repo/oversized.go" 500
git -C "$repo" add oversized.go
printf '// unstaged line 501\n' >> "$repo/oversized.go"
assert_rejected "$repo" oversized.go

repo="$(new_repo oversized-test)"
make_lines "$repo/oversized_test.go" 1001
git -C "$repo" add oversized_test.go
assert_rejected "$repo" oversized_test.go

repo="$(new_repo stale-ratchet)"
make_lines "$repo/legacy.go" 550
printf '600 legacy.go\n' >> "$repo/scripts/go-file-line-budgets.txt"
git -C "$repo" add legacy.go
assert_rejected "$repo" legacy.go

repo="$(new_repo valid-boundaries)"
make_lines "$repo/production.go" 500
make_lines "$repo/production_test.go" 1000
make_lines "$repo/legacy.go" 550
{
  printf '// Code generated by guardrail test. DO NOT EDIT.\n'
  awk 'BEGIN { for (i = 2; i <= 600; i++) print "// generated line " i }'
} > "$repo/generated.go"
printf '550 legacy.go\n' >> "$repo/scripts/go-file-line-budgets.txt"
git -C "$repo" add production.go production_test.go legacy.go generated.go
(cd "$repo" && ./scripts/check-go-file-lines.sh) >/dev/null || fail 'valid boundaries were rejected'

printf 'PASS: Go file line guardrail scenarios\n'
