#!/usr/bin/env bash

set -euo pipefail

unavailable() {
  local selector=$1
  local version=$2
  printf '%s "%s" is not available in this image\n' "$selector" "$version" >&2
  exit 1
}

report_active() {
  printf '%s runtime: requested=%s active=%s\n' "$1" "$2" "$3"
}

mise_version_matches_selector() {
  local installed_version=$1
  local selector=$2
  [[ $installed_version == "$selector" ||
    $installed_version == "$selector".* ||
    $installed_version == "$selector"-* ||
    $installed_version == "$selector"+* ]]
}

prepend_runtime_path() {
  local runtime_bin=$1
  case ":${OMA_RUNTIME_PATH}:" in
    *":${runtime_bin}:"*) ;;
    *) OMA_RUNTIME_PATH="${runtime_bin}${OMA_RUNTIME_PATH:+:${OMA_RUNTIME_PATH}}" ;;
  esac
  case ":${PATH}:" in
    *":${runtime_bin}:"*) ;;
    *) PATH="${runtime_bin}:${PATH}" ;;
  esac
  export PATH
}

persist_runtime_profile() {
  local runtime_profile=$1
  local profile_dir profile_tmp
  profile_dir=$(dirname "$runtime_profile")
  profile_tmp="${runtime_profile}.tmp.$$"
  mkdir -p "$profile_dir"
  {
    printf '# Generated by OMA Runtime Setup.\n'
    printf 'oma_selected_runtime_path=%q\n' "$OMA_RUNTIME_PATH"
    printf '%s\n' \
      'oma_original_ifs=$IFS' \
      'IFS=:' \
      'for oma_runtime_bin in $oma_selected_runtime_path; do' \
      '  oma_filtered_path=' \
      '  for oma_path_segment in $PATH; do' \
      '    [[ $oma_path_segment == "$oma_runtime_bin" ]] && continue' \
      '    oma_filtered_path="${oma_filtered_path}${oma_filtered_path:+:}${oma_path_segment}"' \
      '  done' \
      '  PATH=$oma_filtered_path' \
      'done' \
      'IFS=$oma_original_ifs' \
      'export PATH="${oma_selected_runtime_path}${PATH:+:${PATH}}"'
    printf 'export JAVA_HOME=%q\n' "$OMA_JAVA_HOME"
    printf '%s\n' 'unset oma_selected_runtime_path oma_original_ifs oma_runtime_bin oma_filtered_path oma_path_segment'
  } >"$profile_tmp"
  chmod 0644 "$profile_tmp"
  mv -f "$profile_tmp" "$runtime_profile"
}

activate_python() {
  local active prefix
  if ! prefix=$(pyenv prefix "$ENV_PYTHON_VERSION" 2>/dev/null); then
    unavailable ENV_PYTHON_VERSION "$ENV_PYTHON_VERSION"
  fi
  pyenv global "$ENV_PYTHON_VERSION" >/dev/null
  prepend_runtime_path "${prefix}/bin"
  active=$("${prefix}/bin/python" --version 2>&1)
  report_active Python "$ENV_PYTHON_VERSION" "$active"
}

activate_node() {
  local active installed node_bin
  if ! command -v nvm >/dev/null 2>&1; then
    # nvm is a shell function in the Universal Runtime image.
    # shellcheck disable=SC1091
    source "${NVM_DIR:-/root/.nvm}/nvm.sh"
  fi
  if ! installed=$(nvm version "$ENV_NODE_VERSION" 2>/dev/null); then
    unavailable ENV_NODE_VERSION "$ENV_NODE_VERSION"
  fi
  [[ -n $installed && $installed != N/A ]] || unavailable ENV_NODE_VERSION "$ENV_NODE_VERSION"
  nvm alias default "$ENV_NODE_VERSION" >/dev/null
  nvm use --silent "$ENV_NODE_VERSION" >/dev/null
  node_bin="${NVM_DIR}/versions/node/${installed}/bin"
  prepend_runtime_path "$node_bin"
  active=$("${node_bin}/node" --version)
  report_active Node.js "$ENV_NODE_VERSION" "$active"
}

activate_mise() {
  local selector=$1
  local runtime=$2
  local version=$3
  local active installed installed_runtime installed_version selected_bin selected_version=
  shift 3

  if ! installed=$(env MISE_OFFLINE=1 MISE_NO_CONFIG=1 mise ls --installed --no-header "$runtime" 2>/dev/null); then
    unavailable "$selector" "$version"
  fi
  while read -r installed_runtime installed_version _; do
    if [[ $installed_runtime == "$runtime" ]] && mise_version_matches_selector "$installed_version" "$version"; then
      selected_version=$installed_version
      [[ $installed_version != "$version" ]] || break
    fi
  done <<<"$installed"

  [[ -n $selected_version ]] || unavailable "$selector" "$version"
  env MISE_OFFLINE=1 MISE_NO_CONFIG=1 mise use --global "${runtime}@${selected_version}" >/dev/null
  selected_bin="${MISE_DATA_DIR}/installs/${runtime}/${selected_version}/bin"
  prepend_runtime_path "$selected_bin"
  if [[ $runtime == java ]]; then
    OMA_JAVA_HOME=${selected_bin%/bin}
  fi
  active=$("$@" 2>&1 | sed -n '1p')
  report_active "$runtime" "$version" "$active"
}

activate_rust() {
  local active available=false rust_bin toolchain
  while IFS= read -r toolchain; do
    toolchain=${toolchain%% *}
    if [[ $toolchain == "$ENV_RUST_VERSION" || $toolchain == "$ENV_RUST_VERSION"-* ]]; then
      available=true
      break
    fi
  done < <(rustup toolchain list)
  [[ $available == true ]] || unavailable ENV_RUST_VERSION "$ENV_RUST_VERSION"
  rustup default "$toolchain" >/dev/null
  rust_bin="${RUSTUP_HOME}/toolchains/${toolchain}/bin"
  prepend_runtime_path "$rust_bin"
  active=$("${rust_bin}/rustc" --version)
  report_active Rust "$ENV_RUST_VERSION" "$active"
}

activate_php() {
  local active prefix
  local installed="${ENV_PHP_VERSION}snapshot"
  if ! prefix=$(phpenv prefix "$installed" 2>/dev/null); then
    unavailable ENV_PHP_VERSION "$ENV_PHP_VERSION"
  fi
  phpenv global "$installed" >/dev/null
  phpenv rehash >/dev/null
  prepend_runtime_path "${prefix}/bin"
  active=$("${prefix}/bin/php" --version | sed -n '1p')
  report_active PHP "$ENV_PHP_VERSION" "$active"
}

activate_swift() {
  local active
  swiftly list | awk -v version="$ENV_SWIFT_VERSION" '
    {
      text = $0
      while ((position = index(text, version)) > 0) {
        before = position > 1 ? substr(text, position - 1, 1) : ""
        after = substr(text, position + length(version), 1)
        if ((before == "" || before !~ /[0-9]/) && (after == "" || after !~ /[0-9]/)) {
          found = 1
          next
        }
        text = substr(text, position + length(version))
      }
    }
    END { exit found ? 0 : 1 }
  ' ||
    unavailable ENV_SWIFT_VERSION "$ENV_SWIFT_VERSION"
  swiftly use "$ENV_SWIFT_VERSION" >/dev/null
  prepend_runtime_path "$SWIFTLY_BIN_DIR"
  active=$("${SWIFTLY_BIN_DIR}/swift" --version | sed -n '1p')
  report_active Swift "$ENV_SWIFT_VERSION" "$active"
}

oma_setup_runtime() {
  local runtime_profile=$1

  # The public runtime contract only accepts neutral ENV_* selectors. Remove
  # provider-prefixed selectors before invoking any Runtime manager.
  while IFS='=' read -r name _; do
    case "$name" in
      *_ENV_*_VERSION) unset "$name" ;;
    esac
  done < <(env)
  unset OMA_RUNTIME_PROFILE

  export PYENV_ROOT=${PYENV_ROOT:-/root/.pyenv}
  export NVM_DIR=${NVM_DIR:-/root/.nvm}
  export PHPENV_ROOT=${PHPENV_ROOT:-/root/.phpenv}
  export SWIFTLY_BIN_DIR=${SWIFTLY_BIN_DIR:-/root/.swiftly/bin}
  export CARGO_HOME=${CARGO_HOME:-/root/.cargo}
  export RUSTUP_HOME=${RUSTUP_HOME:-/root/.rustup}
  export MISE_DATA_DIR=${MISE_DATA_DIR:-/root/.local/share/mise}
  export PATH="${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:${CARGO_HOME}/bin:${PHPENV_ROOT}/bin:${PHPENV_ROOT}/shims:${SWIFTLY_BIN_DIR}:${MISE_DATA_DIR}/shims:${PATH}"

  export ENV_PYTHON_VERSION=${ENV_PYTHON_VERSION:-3.12}
  export ENV_NODE_VERSION=${ENV_NODE_VERSION:-22}
  export ENV_RUBY_VERSION=${ENV_RUBY_VERSION:-3.4.4}
  export ENV_RUST_VERSION=${ENV_RUST_VERSION:-1.89.0}
  export ENV_GO_VERSION=${ENV_GO_VERSION:-1.25.1}
  export ENV_BUN_VERSION=${ENV_BUN_VERSION:-1.2.14}
  export ENV_PHP_VERSION=${ENV_PHP_VERSION:-8.4}
  export ENV_JAVA_VERSION=${ENV_JAVA_VERSION:-21}
  export ENV_SWIFT_VERSION=${ENV_SWIFT_VERSION:-6.1}
  OMA_RUNTIME_PATH=
  OMA_JAVA_HOME=

  activate_python
  activate_node
  activate_mise ENV_RUBY_VERSION ruby "$ENV_RUBY_VERSION" ruby --version
  activate_rust
  activate_mise ENV_GO_VERSION go "$ENV_GO_VERSION" env GOTOOLCHAIN=local go version
  activate_mise ENV_BUN_VERSION bun "$ENV_BUN_VERSION" bun --version
  activate_php
  activate_mise ENV_JAVA_VERSION java "$ENV_JAVA_VERSION" java --version
  activate_swift
  persist_runtime_profile "$runtime_profile"
  unset OMA_RUNTIME_PATH OMA_JAVA_HOME
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  oma_setup_runtime /etc/profile.d/oma-runtime.sh
fi
