// Code generated by sqlmapgen; DO NOT EDIT.

package db

import (
	"context"
	"github.com/google/uuid"
	yourbatis "github.com/superduck-ai/yourbatis"
)

type adminAPIKeyMapper struct {
	executor yourbatis.Executor
}

var _ AdminAPIKeyMapper = (*adminAPIKeyMapper)(nil)

func NewAdminAPIKeyMapper(executor yourbatis.Executor) AdminAPIKeyMapper {
	return &adminAPIKeyMapper{executor: executor}
}

var adminAPIKeyMapperFindByExternalIDStatement = yourbatis.Statement{
	ID:     "AdminAPIKeyMapper.FindByExternalID",
	Source: "./admin_api_keys_mapper.xml:18",
	Kind:   yourbatis.StatementSelect,
}

func scanAdminAPIKeyMapperFindByExternalID(row yourbatis.Scanner) (AdminAPIKey, error) {
	var result AdminAPIKey
	err := row.Scan(
		&result.UUID,
		&result.ExternalID,
		&result.WorkspaceUUID,
		&result.WorkspaceExternalID,
		&result.CreatedByUserUUID,
		&result.CreatedByUserExternalID,
		&result.Name,
		&result.PartialKeyHint,
		&result.Status,
		&result.CreatedAt,
		&result.UpdatedAt,
		&result.ExpiresAt,
	)
	return result, err
}

func buildAdminAPIKeyMapperFindByExternalID(dialect yourbatis.Dialect, organizationUUID string, externalID string) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        SELECT\n        ")
	builder.BeginSQLNode()
	builder.Text("\n        ak.uuid,\n        ak.external_id,\n        ak.workspace_uuid,\n        w.external_id AS workspace_external_id,\n        ak.created_by_user_uuid,\n        u.external_id AS created_by_user_external_id,\n        ak.name,\n        ak.partial_key_hint,\n        ak.status,\n        ak.created_at,\n        ak.updated_at,\n        ak.expires_at\n    ")
	builder.BeginSQLNode()
	builder.Text("\n        FROM api_keys ak\n        JOIN workspaces w ON w.uuid = ak.workspace_uuid\n        LEFT JOIN users u ON u.uuid = ak.created_by_user_uuid\n        WHERE w.organization_uuid = ")
	builder.Arg("organizationUUID", organizationUUID)
	builder.Text("\n        AND ak.external_id = ")
	builder.Arg("externalID", externalID)
	builder.Text("\n    ")
	return builder.Build()
}

func (mapper *adminAPIKeyMapper) FindByExternalID(ctx context.Context, organizationUUID string, externalID string) (AdminAPIKey, bool, error) {
	__yourbatisBound := buildAdminAPIKeyMapperFindByExternalID(mapper.executor.Dialect(), organizationUUID, externalID)
	return yourbatis.SelectOptional(ctx, mapper.executor, adminAPIKeyMapperFindByExternalIDStatement, __yourbatisBound, scanAdminAPIKeyMapperFindByExternalID)
}

var adminAPIKeyMapperFindPageAnchorByExternalIDStatement = yourbatis.Statement{
	ID:     "AdminAPIKeyMapper.FindPageAnchorByExternalID",
	Source: "./admin_api_keys_mapper.xml:28",
	Kind:   yourbatis.StatementSelect,
}

func scanAdminAPIKeyMapperFindPageAnchorByExternalID(row yourbatis.Scanner) (adminAPIKeyPageAnchor, error) {
	var result adminAPIKeyPageAnchor
	err := row.Scan(
		&result.CreatedAt,
		&result.UUID,
	)
	return result, err
}

func buildAdminAPIKeyMapperFindPageAnchorByExternalID(dialect yourbatis.Dialect, organizationUUID string, externalID string) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        SELECT ak.created_at, ak.uuid\n        FROM api_keys ak\n        JOIN workspaces w ON w.uuid = ak.workspace_uuid\n        WHERE w.organization_uuid = ")
	builder.Arg("organizationUUID", organizationUUID)
	builder.Text("\n        AND ak.external_id = ")
	builder.Arg("externalID", externalID)
	builder.Text("\n    ")
	return builder.Build()
}

func (mapper *adminAPIKeyMapper) FindPageAnchorByExternalID(ctx context.Context, organizationUUID string, externalID string) (adminAPIKeyPageAnchor, bool, error) {
	__yourbatisBound := buildAdminAPIKeyMapperFindPageAnchorByExternalID(mapper.executor.Dialect(), organizationUUID, externalID)
	return yourbatis.SelectOptional(ctx, mapper.executor, adminAPIKeyMapperFindPageAnchorByExternalIDStatement, __yourbatisBound, scanAdminAPIKeyMapperFindPageAnchorByExternalID)
}

var adminAPIKeyMapperListPageStatement = yourbatis.Statement{
	ID:     "AdminAPIKeyMapper.ListPage",
	Source: "./admin_api_keys_mapper.xml:36",
	Kind:   yourbatis.StatementSelect,
}

func scanAdminAPIKeyMapperListPage(row yourbatis.Scanner) (AdminAPIKey, error) {
	var result AdminAPIKey
	err := row.Scan(
		&result.UUID,
		&result.ExternalID,
		&result.WorkspaceUUID,
		&result.WorkspaceExternalID,
		&result.CreatedByUserUUID,
		&result.CreatedByUserExternalID,
		&result.Name,
		&result.PartialKeyHint,
		&result.Status,
		&result.CreatedAt,
		&result.UpdatedAt,
		&result.ExpiresAt,
	)
	return result, err
}

func buildAdminAPIKeyMapperListPage(dialect yourbatis.Dialect, organizationUUID string, workspaceExternalID string, createdByUserExternalID string, status string, anchor *adminAPIKeyPageAnchor, before bool, limit int) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        SELECT\n        ")
	builder.BeginSQLNode()
	builder.Text("\n        ak.uuid,\n        ak.external_id,\n        ak.workspace_uuid,\n        w.external_id AS workspace_external_id,\n        ak.created_by_user_uuid,\n        u.external_id AS created_by_user_external_id,\n        ak.name,\n        ak.partial_key_hint,\n        ak.status,\n        ak.created_at,\n        ak.updated_at,\n        ak.expires_at\n    ")
	builder.BeginSQLNode()
	builder.Text("\n        FROM api_keys ak\n        JOIN workspaces w ON w.uuid = ak.workspace_uuid\n        LEFT JOIN users u ON u.uuid = ak.created_by_user_uuid\n        ")
	trim1 := yourbatis.NewBuilder(dialect)
	trim1.BeginSQLNode()
	trim1.Text("\n            w.organization_uuid = ")
	trim1.Arg("organizationUUID", organizationUUID)
	trim1.Text("\n            ")
	if workspaceExternalID != "" {
		trim1.BeginSQLNode()
		trim1.Text("\n                AND w.external_id = ")
		trim1.Arg("workspaceExternalID", workspaceExternalID)
		trim1.Text("\n            ")
	}
	trim1.BeginSQLNode()
	trim1.Text("\n            ")
	if createdByUserExternalID != "" {
		trim1.BeginSQLNode()
		trim1.Text("\n                AND u.external_id = ")
		trim1.Arg("createdByUserExternalID", createdByUserExternalID)
		trim1.Text("\n            ")
	}
	trim1.BeginSQLNode()
	trim1.Text("\n            ")
	if status != "" {
		trim1.BeginSQLNode()
		trim1.Text("\n                AND ak.status = ")
		trim1.Arg("status", status)
		trim1.Text("\n            ")
	}
	trim1.BeginSQLNode()
	trim1.Text("\n            ")
	if anchor != nil {
		trim1.BeginSQLNode()
		trim1.Text("\n                ")
		if before {
			trim1.BeginSQLNode()
			trim1.Text("\n                        AND (ak.created_at, ak.uuid) > (")
			trim1.Arg("anchor.CreatedAt", anchor.CreatedAt)
			trim1.Text(", ")
			trim1.Arg("anchor.UUID", anchor.UUID)
			trim1.Text(")\n                    ")
		} else {
			trim1.BeginSQLNode()
			trim1.Text("\n                        AND (ak.created_at, ak.uuid) < (")
			trim1.Arg("anchor.CreatedAt", anchor.CreatedAt)
			trim1.Text(", ")
			trim1.Arg("anchor.UUID", anchor.UUID)
			trim1.Text(")\n                    ")
		}
		trim1.BeginSQLNode()
		trim1.Text("\n            ")
	}
	trim1.BeginSQLNode()
	trim1.Text("\n        ")
	builder.BeginSQLNode()
	builder.AppendTrimmed(trim1, "WHERE ", []string{"AND ", "OR ", "AND\n", "OR\n", "AND\r", "OR\r", "AND\t", "OR\t"}, "", []string(nil))
	builder.BeginSQLNode()
	builder.Text("\n        ")
	if before {
		builder.BeginSQLNode()
		builder.Text("\n                ORDER BY ak.created_at ASC, ak.uuid ASC\n            ")
	} else {
		builder.BeginSQLNode()
		builder.Text("\n                ORDER BY ak.created_at DESC, ak.uuid DESC\n            ")
	}
	builder.BeginSQLNode()
	builder.Text("\n        LIMIT ")
	builder.Arg("limit", limit)
	builder.Text("\n    ")
	return builder.Build()
}

func (mapper *adminAPIKeyMapper) ListPage(ctx context.Context, organizationUUID string,
	workspaceExternalID, createdByUserExternalID, status string,
	anchor *adminAPIKeyPageAnchor, before bool, limit int) ([]AdminAPIKey, error) {
	__yourbatisBound := buildAdminAPIKeyMapperListPage(mapper.executor.Dialect(), organizationUUID, workspaceExternalID, createdByUserExternalID, status, anchor, before, limit)
	return yourbatis.SelectMany(ctx, mapper.executor, adminAPIKeyMapperListPageStatement, __yourbatisBound, scanAdminAPIKeyMapperListPage)
}

var adminAPIKeyMapperInsertStatement = yourbatis.Statement{
	ID:     "AdminAPIKeyMapper.Insert",
	Source: "./admin_api_keys_mapper.xml:75",
	Kind:   yourbatis.StatementInsert,
}

func buildAdminAPIKeyMapperInsert(dialect yourbatis.Dialect, params insertAdminAPIKeyParams) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        INSERT INTO api_keys (\n            uuid,\n            external_id,\n            workspace_uuid,\n            key_hash,\n            status,\n            created_by_user_uuid,\n            name,\n            partial_key_hint,\n            expires_at\n        ) VALUES (\n            ")
	builder.Arg("params.UUID", params.UUID)
	builder.Text(",\n            ")
	builder.Arg("params.ExternalID", params.ExternalID)
	builder.Text(",\n            ")
	builder.Arg("params.WorkspaceUUID", params.WorkspaceUUID)
	builder.Text(",\n            ")
	builder.Arg("params.KeyHash", params.KeyHash, yourbatis.Sensitive())
	builder.Text(",\n            'active',\n            ")
	builder.Arg("params.CreatedByUserUUID", params.CreatedByUserUUID)
	builder.Text(",\n            ")
	builder.Arg("params.Name", params.Name)
	builder.Text(",\n            ")
	builder.Arg("params.PartialKeyHint", params.PartialKeyHint)
	builder.Text(",\n            ")
	builder.Arg("params.ExpiresAt", params.ExpiresAt)
	builder.Text("\n        )\n    ")
	return builder.Build()
}

func (mapper *adminAPIKeyMapper) Insert(ctx context.Context, params insertAdminAPIKeyParams) error {
	__yourbatisBound := buildAdminAPIKeyMapperInsert(mapper.executor.Dialect(), params)
	return yourbatis.Execute(ctx, mapper.executor, adminAPIKeyMapperInsertStatement, __yourbatisBound)
}

var adminAPIKeyMapperUpdateByExternalIDStatement = yourbatis.Statement{
	ID:     "AdminAPIKeyMapper.UpdateByExternalID",
	Source: "./admin_api_keys_mapper.xml:99",
	Kind:   yourbatis.StatementUpdate,
}

func buildAdminAPIKeyMapperUpdateByExternalID(dialect yourbatis.Dialect, organizationUUID string, externalID string, setName bool, name string, setStatus bool, status string) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        UPDATE api_keys ak\n        ")
	trim1 := yourbatis.NewBuilder(dialect)
	trim1.BeginSQLNode()
	trim1.Text("\n            ")
	if setName {
		trim1.BeginSQLNode()
		trim1.Text("\n                name = ")
		trim1.Arg("name", name)
		trim1.Text(",\n            ")
	}
	trim1.BeginSQLNode()
	trim1.Text("\n            ")
	if setStatus {
		trim1.BeginSQLNode()
		trim1.Text("\n                status = ")
		trim1.Arg("status", status)
		trim1.Text(",\n            ")
	}
	trim1.BeginSQLNode()
	trim1.Text("\n            updated_at = NOW()\n        ")
	builder.BeginSQLNode()
	builder.AppendTrimmed(trim1, "SET ", []string{","}, "", []string{","})
	builder.BeginSQLNode()
	builder.Text("\n        FROM workspaces w\n        WHERE ak.workspace_uuid = w.uuid\n        AND w.organization_uuid = ")
	builder.Arg("organizationUUID", organizationUUID)
	builder.Text("\n        AND ak.external_id = ")
	builder.Arg("externalID", externalID)
	builder.Text("\n    ")
	return builder.Build()
}

func (mapper *adminAPIKeyMapper) UpdateByExternalID(ctx context.Context, organizationUUID string, externalID string,
	setName bool, name string, setStatus bool, status string) (int64, error) {
	__yourbatisBound := buildAdminAPIKeyMapperUpdateByExternalID(mapper.executor.Dialect(), organizationUUID, externalID, setName, name, setStatus, status)
	return yourbatis.ExecuteRows(ctx, mapper.executor, adminAPIKeyMapperUpdateByExternalIDStatement, __yourbatisBound)
}

var adminAPIKeyMapperUpdateStatusByUUIDStatement = yourbatis.Statement{
	ID:     "AdminAPIKeyMapper.UpdateStatusByUUID",
	Source: "./admin_api_keys_mapper.xml:116",
	Kind:   yourbatis.StatementUpdate,
}

func buildAdminAPIKeyMapperUpdateStatusByUUID(dialect yourbatis.Dialect, apiKeyUUID uuid.UUID, status string) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        UPDATE api_keys\n        SET status = ")
	builder.Arg("status", status)
	builder.Text(",\n            updated_at = NOW()\n        WHERE uuid = ")
	builder.Arg("apiKeyUUID", apiKeyUUID)
	builder.Text("\n    ")
	return builder.Build()
}

func (mapper *adminAPIKeyMapper) UpdateStatusByUUID(ctx context.Context, apiKeyUUID uuid.UUID, status string) (int64, error) {
	__yourbatisBound := buildAdminAPIKeyMapperUpdateStatusByUUID(mapper.executor.Dialect(), apiKeyUUID, status)
	return yourbatis.ExecuteRows(ctx, mapper.executor, adminAPIKeyMapperUpdateStatusByUUIDStatement, __yourbatisBound)
}
