// Code generated by sqlmapgen; DO NOT EDIT.

package db

import (
	"context"
	yourbatis "github.com/superduck-ai/yourbatis"
)

type consoleAPIKeyMapper struct {
	executor yourbatis.Executor
}

var _ ConsoleAPIKeyMapper = (*consoleAPIKeyMapper)(nil)

func NewConsoleAPIKeyMapper(executor yourbatis.Executor) ConsoleAPIKeyMapper {
	return &consoleAPIKeyMapper{executor: executor}
}

var consoleAPIKeyMapperListStatement = yourbatis.Statement{
	ID:     "ConsoleAPIKeyMapper.List",
	Source: "./console_api_keys_mapper.xml:39",
	Kind:   yourbatis.StatementSelect,
}

func scanConsoleAPIKeyMapperList(row yourbatis.Scanner) (consoleAPIKeyRow, error) {
	var result consoleAPIKeyRow
	err := row.Scan(
		&result.ID,
		&result.WorkspaceAPIKeyUUID,
		&result.OrgUUID,
		&result.WorkspaceUUID,
		&result.WorkspaceDisplayID,
		&result.Name,
		&result.KeyPrefix,
		&result.KeySuffix,
		&result.Status,
		&result.CreatedByUserUUID,
		&result.LastUsedAt,
		&result.ExpiresAt,
		&result.ArchivedAt,
		&result.CreatedAt,
		&result.UpdatedAt,
	)
	return result, err
}

func buildConsoleAPIKeyMapperList(dialect yourbatis.Dialect, organizationUUID string, workspaceUUID string) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        SELECT\n        ")
	builder.BeginSQLNode()
	builder.Text("\n        external_id AS id,\n        api_key_ref_uuid AS workspace_api_key_uuid,\n        organization_uuid AS org_uuid,\n        workspace_uuid,\n        workspace_display_id,\n        name,\n        key_prefix,\n        key_suffix,\n        status,\n        created_by_user_ref_uuid AS created_by_user_uuid,\n        last_used_at,\n        expires_at,\n        archived_at,\n        created_at,\n        updated_at\n    ")
	builder.BeginSQLNode()
	builder.Text("\n        FROM console_api_keys\n        WHERE organization_uuid = ")
	builder.Arg("organizationUUID", organizationUUID)
	builder.Text("\n        ")
	if workspaceUUID != "" {
		builder.BeginSQLNode()
		builder.Text("\n            AND workspace_uuid = ")
		builder.Arg("workspaceUUID", workspaceUUID)
		builder.Text("\n        ")
	}
	builder.BeginSQLNode()
	builder.Text("\n        ORDER BY created_at DESC, external_id DESC\n    ")
	return builder.Build()
}

func (mapper *consoleAPIKeyMapper) List(ctx context.Context, organizationUUID, workspaceUUID string) ([]consoleAPIKeyRow, error) {
	__yourbatisBound := buildConsoleAPIKeyMapperList(mapper.executor.Dialect(), organizationUUID, workspaceUUID)
	return yourbatis.SelectMany(ctx, mapper.executor, consoleAPIKeyMapperListStatement, __yourbatisBound, scanConsoleAPIKeyMapperList)
}

var consoleAPIKeyMapperCountUnarchivedStatement = yourbatis.Statement{
	ID:     "ConsoleAPIKeyMapper.CountUnarchived",
	Source: "./console_api_keys_mapper.xml:50",
	Kind:   yourbatis.StatementSelect,
}

func scanConsoleAPIKeyMapperCountUnarchived(row yourbatis.Scanner) (int64, error) {
	var result int64
	err := row.Scan(&result)
	return result, err
}

func buildConsoleAPIKeyMapperCountUnarchived(dialect yourbatis.Dialect, organizationUUID string, workspaceUUID string) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        SELECT COUNT(*)\n        FROM console_api_keys\n        WHERE organization_uuid = ")
	builder.Arg("organizationUUID", organizationUUID)
	builder.Text("\n        AND workspace_uuid = ")
	builder.Arg("workspaceUUID", workspaceUUID)
	builder.Text("\n        AND archived_at IS NULL\n    ")
	return builder.Build()
}

func (mapper *consoleAPIKeyMapper) CountUnarchived(ctx context.Context, organizationUUID, workspaceUUID string) (int64, error) {
	__yourbatisBound := buildConsoleAPIKeyMapperCountUnarchived(mapper.executor.Dialect(), organizationUUID, workspaceUUID)
	return yourbatis.SelectOne(ctx, mapper.executor, consoleAPIKeyMapperCountUnarchivedStatement, __yourbatisBound, scanConsoleAPIKeyMapperCountUnarchived)
}

var consoleAPIKeyMapperCreatorExistsStatement = yourbatis.Statement{
	ID:     "ConsoleAPIKeyMapper.CreatorExists",
	Source: "./console_api_keys_mapper.xml:58",
	Kind:   yourbatis.StatementSelect,
}

func scanConsoleAPIKeyMapperCreatorExists(row yourbatis.Scanner) (bool, error) {
	var result bool
	err := row.Scan(&result)
	return result, err
}

func buildConsoleAPIKeyMapperCreatorExists(dialect yourbatis.Dialect, organizationUUID string, userUUID string) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        SELECT EXISTS (\n            SELECT 1\n            FROM users u\n            WHERE u.organization_uuid = ")
	builder.Arg("organizationUUID", organizationUUID)
	builder.Text("\n            AND u.uuid = ")
	builder.Arg("userUUID", userUUID)
	builder.Text("\n            AND u.deleted_at IS NULL\n        )\n    ")
	return builder.Build()
}

func (mapper *consoleAPIKeyMapper) CreatorExists(ctx context.Context, organizationUUID, userUUID string) (bool, error) {
	__yourbatisBound := buildConsoleAPIKeyMapperCreatorExists(mapper.executor.Dialect(), organizationUUID, userUUID)
	return yourbatis.SelectOne(ctx, mapper.executor, consoleAPIKeyMapperCreatorExistsStatement, __yourbatisBound, scanConsoleAPIKeyMapperCreatorExists)
}

var consoleAPIKeyMapperInsertStatement = yourbatis.Statement{
	ID:     "ConsoleAPIKeyMapper.Insert",
	Source: "./console_api_keys_mapper.xml:68",
	Kind:   yourbatis.StatementInsert,
}

func scanConsoleAPIKeyMapperInsert(row yourbatis.Scanner) (consoleAPIKeyRow, error) {
	var result consoleAPIKeyRow
	err := row.Scan(
		&result.ID,
		&result.WorkspaceAPIKeyUUID,
		&result.OrgUUID,
		&result.WorkspaceUUID,
		&result.WorkspaceDisplayID,
		&result.Name,
		&result.KeyPrefix,
		&result.KeySuffix,
		&result.Status,
		&result.CreatedByUserUUID,
		&result.LastUsedAt,
		&result.ExpiresAt,
		&result.ArchivedAt,
		&result.CreatedAt,
		&result.UpdatedAt,
	)
	return result, err
}

func buildConsoleAPIKeyMapperInsert(dialect yourbatis.Dialect, params insertConsoleAPIKeyQuery) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        INSERT INTO console_api_keys (\n            external_id,\n            api_key_ref_uuid,\n            organization_uuid,\n            workspace_uuid,\n            workspace_display_id,\n            name,\n            key_prefix,\n            key_suffix,\n            key_hash,\n            status,\n            created_by_user_ref_uuid,\n            expires_at\n        ) VALUES (\n            ")
	builder.Arg("params.ExternalID", params.ExternalID)
	builder.Text(",\n            ")
	builder.Arg("params.APIKeyUUID", params.APIKeyUUID)
	builder.Text(",\n            ")
	builder.Arg("params.OrganizationUUID", params.OrganizationUUID)
	builder.Text(",\n            ")
	builder.Arg("params.WorkspaceUUID", params.WorkspaceUUID)
	builder.Text(",\n            ")
	builder.Arg("params.WorkspaceDisplayID", params.WorkspaceDisplayID)
	builder.Text(",\n            ")
	builder.Arg("params.Name", params.Name)
	builder.Text(",\n            ")
	builder.Arg("params.KeyPrefix", params.KeyPrefix, yourbatis.Sensitive())
	builder.Text(",\n            ")
	builder.Arg("params.KeySuffix", params.KeySuffix, yourbatis.Sensitive())
	builder.Text(",\n            ")
	builder.Arg("params.KeyHash", params.KeyHash, yourbatis.Sensitive())
	builder.Text(",\n            'active',\n            ")
	builder.Arg("params.CreatedByUserUUID", params.CreatedByUserUUID)
	builder.Text(",\n            ")
	builder.Arg("params.ExpiresAt", params.ExpiresAt)
	builder.Text("\n        )\n        RETURNING\n        ")
	builder.BeginSQLNode()
	builder.Text("\n        external_id AS id,\n        api_key_ref_uuid AS workspace_api_key_uuid,\n        organization_uuid AS org_uuid,\n        workspace_uuid,\n        workspace_display_id,\n        name,\n        key_prefix,\n        key_suffix,\n        status,\n        created_by_user_ref_uuid AS created_by_user_uuid,\n        last_used_at,\n        expires_at,\n        archived_at,\n        created_at,\n        updated_at\n    ")
	builder.BeginSQLNode()
	builder.Text("\n    ")
	return builder.Build()
}

func (mapper *consoleAPIKeyMapper) Insert(ctx context.Context, params insertConsoleAPIKeyQuery) (consoleAPIKeyRow, error) {
	__yourbatisBound := buildConsoleAPIKeyMapperInsert(mapper.executor.Dialect(), params)
	return yourbatis.QueryOne(ctx, mapper.executor, consoleAPIKeyMapperInsertStatement, __yourbatisBound, scanConsoleAPIKeyMapperInsert)
}

var consoleAPIKeyMapperUpdateStatusStatement = yourbatis.Statement{
	ID:     "ConsoleAPIKeyMapper.UpdateStatus",
	Source: "./console_api_keys_mapper.xml:100",
	Kind:   yourbatis.StatementUpdate,
}

func scanConsoleAPIKeyMapperUpdateStatus(row yourbatis.Scanner) (consoleAPIKeyRow, error) {
	var result consoleAPIKeyRow
	err := row.Scan(
		&result.ID,
		&result.WorkspaceAPIKeyUUID,
		&result.OrgUUID,
		&result.WorkspaceUUID,
		&result.WorkspaceDisplayID,
		&result.Name,
		&result.KeyPrefix,
		&result.KeySuffix,
		&result.Status,
		&result.CreatedByUserUUID,
		&result.LastUsedAt,
		&result.ExpiresAt,
		&result.ArchivedAt,
		&result.CreatedAt,
		&result.UpdatedAt,
	)
	return result, err
}

func buildConsoleAPIKeyMapperUpdateStatus(dialect yourbatis.Dialect, params updateConsoleAPIKeyStatusQuery) yourbatis.BoundSQL {
	builder := yourbatis.NewBuilder(dialect)
	builder.BeginSQLNode()
	builder.Text("\n        UPDATE console_api_keys\n        SET status = ")
	builder.Arg("params.Status", params.Status)
	builder.Text(",\n            archived_at = CASE\n                WHEN ")
	builder.Arg("params.Status", params.Status)
	builder.Text(" = 'archived' THEN COALESCE(archived_at, NOW())\n                ELSE NULL\n            END,\n            updated_at = NOW()\n        WHERE organization_uuid = ")
	builder.Arg("params.OrganizationUUID", params.OrganizationUUID)
	builder.Text("\n        AND workspace_uuid = ")
	builder.Arg("params.WorkspaceUUID", params.WorkspaceUUID)
	builder.Text("\n        AND external_id = ")
	builder.Arg("params.ExternalID", params.ExternalID)
	builder.Text("\n        RETURNING\n        ")
	builder.BeginSQLNode()
	builder.Text("\n        external_id AS id,\n        api_key_ref_uuid AS workspace_api_key_uuid,\n        organization_uuid AS org_uuid,\n        workspace_uuid,\n        workspace_display_id,\n        name,\n        key_prefix,\n        key_suffix,\n        status,\n        created_by_user_ref_uuid AS created_by_user_uuid,\n        last_used_at,\n        expires_at,\n        archived_at,\n        created_at,\n        updated_at\n    ")
	builder.BeginSQLNode()
	builder.Text("\n    ")
	return builder.Build()
}

func (mapper *consoleAPIKeyMapper) UpdateStatus(ctx context.Context, params updateConsoleAPIKeyStatusQuery) (consoleAPIKeyRow, error) {
	__yourbatisBound := buildConsoleAPIKeyMapperUpdateStatus(mapper.executor.Dialect(), params)
	return yourbatis.QueryOne(ctx, mapper.executor, consoleAPIKeyMapperUpdateStatusStatement, __yourbatisBound, scanConsoleAPIKeyMapperUpdateStatus)
}
